---
title: "The journey of the Tour de France"
author: "Najia et Léane"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    vertical_layout: fill
    navbar:
params:
  setup_path: ../resources/
---

<style>                     
.navbar {
  background-color:#f2e524;
  border-color:#46ACC8;
}
.navbar-brand {
color:black!important;
}


</style>   


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggplot2)
library(plotly)
library(readr)
library(dplyr)
library(geosphere)
library(ggplot2)
library(RJSONIO)
library(plotly)
library(maps)
library(mapdata)
library(ggmap)
library(rgdal)
library(raster)
library(ggnewscale)
```

Overview
======================================================================

Column {data-width=650}
----------------------------------------------------------------------

### Evolution of stages types over time 

```{r data, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
tdf=read.csv('stages_TDF.csv',sep=';')
tdf$Date <- as.Date(tdf$Date, format = "%Y-%m-%d")
flat=c('Flat','Flat stage','Flat Stage','Half Stage','Plain stage','Plain stage with cobblestones',"Flat cobblestone stage" )
hilly=c('Hilly','Hilly stage','Transition stage','Half Stage','Intermediate stage')
mountain=c('Mountain',"High mountain stage","Medium mountain stage","Mountain Stage" ,"Stage with mountain(s)" ,"Mountain stage" ,"Stage with mountain")
ind_timetrial=c('individual time trial',"Mountain time trial","Individual time trial")
team_timetrial=c('team time trial',"Team time trial")
type=list(flat,hilly,mountain,ind_timetrial,team_timetrial)  #liste de vecteurs
for (i in 1:length(tdf$Type)) {
  for (k in type) {
    if (tdf$Type[i]%in% k) {
      tdf$Type[i]=k[1]
      
    }
  }
}
unique(tdf$Type) #double check
tdf$Year= as.numeric(format(tdf$Date, format="%Y"))
tdf %>%
  group_by(Year) %>%
  summarise(dist_totale = sum(Distance))%>%
  as.data.frame()-> dist_totale
tdf_bis=merge(tdf,dist_totale,by='Year')
tdf_bis %>%
  group_by(Year) %>%
  summarise(nb_stages=table(as.numeric(Stage)))%>%
  count()%>%
  as.data.frame() -> nb_stages
tdf_bis $Type = factor(tdf_bis$Type, levels = c("Flat",  "team time trial","individual time trial", "Hilly","Mountain"), ordered = TRUE)
tdf_bis=merge(tdf_bis,nb_stages,by='Year')
```


```{r ggplot2, echo = F,  eval = TRUE,  message = FALSE, warning=FALSE, fig.width = 10}
g1 <- ggplot(data=tdf_bis,aes(as.numeric(Year))) +
  geom_bar(position = "fill",width = 2,alpha =1,aes(fill = Type))+
  geom_smooth(aes(y=n/25),linetype='dashed',colour='white',se=F)+
  scale_y_continuous(expand = c(0, 0),sec.axis = sec_axis(trans = ~.*25, name = "Number of stages")) +
  
  scale_x_continuous(expand=c(0,0))+

  geom_rect(aes(xmin = 1914, xmax = 1919, ymin = 0, ymax = 1),fill='light grey')+
  
  geom_text(aes(1917,0.5), label = "world war I", angle =270, size = 4,colour='black')+
  geom_rect(aes(xmin = 1939, xmax = 1947, ymin = 0, ymax = 1),fill='light grey')+
  geom_text(aes(1943,0.5), label ="world war II", angle=270, size = 4,colour='black')+
  theme(legend.position="left") +  
  theme(axis.title = element_text(size=12),
    axis.title.y.right = element_text(size=12))+

  
  theme(legend.title=element_text(size=15),legend.text = element_text( size=15))+ 
  
  labs( y = "Proportion", x="Years")
g1
```


### Evolution of distance over time



```{r ggplot1, echo = F,  eval = TRUE,  message = FALSE, warning=FALSE, fig.width = 10}

g2 <- ggplot(data=tdf_bis,aes(x=Year)) +
  geom_smooth(aes(y=Distance,color=Type),se=F)+
 
  geom_smooth(aes(x=Year,y=dist_totale/10,color='total'),color='#C57B57',linetype = "dashed",se=F,size=2)+
  scale_y_continuous(expand=c(0,0), name = "Distance per stage",
    sec.axis = sec_axis( trans=~.*10, name="Total distance")
  )+
  scale_x_continuous(expand=c(0,0))+
  
  labs(colour = 'Stage type',face='bold') + 
  labs(y='Distance in km',x='Years' )+ 
  
  geom_rect(aes(xmin = 1914, xmax = 1919, ymin = 0, ymax = 600),fill='#C2D9D4')+
  
  geom_text(aes(1917,400), label = "world war I", angle =270, size = 4,colour='#52605C')+
  geom_rect(aes(xmin = 1939, xmax = 1947, ymin = 0, ymax = 600),fill='#C2D9D4')+
  geom_text(aes(1943,400), label ="world war II", angle=270, size = 4,colour='#52605C')+
  
  theme(
  panel.background = element_rect(fill = "#E3EBE9",
                                colour = "#E3EBE9",
                                size = 0.5, linetype = "solid"),
  panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white")) + 
  theme(
    axis.title.y.right = element_text(color = '#C57B57',size=12))+
  
  theme(axis.title = element_text(size=12))+
  theme(axis.text.y.right = element_text(size=12))+
  theme(legend.position="left")+
  theme(legend.title=element_text(size=15),legend.text = element_text( size=15)) 

      
g2
```






Column 
-----------------------------------------------------------------


### Evolution of stages over time

```{r data2, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
# Importation des données 
stages_TDF <- read.csv("./TDF/stages_TDFcoord2.csv", sep = ",")
stages_TDF <- stages_TDF[-1]
# Construction d'un nouveau dataframe avec les informations par ville
Origin_Type = stages_TDF[c("Origin", "Type", "lat_Origin", "lon_Origin", "Date")]
colnames(Origin_Type) = c("Ville", "Type", "lat", "lon", "Date")
Destination_Type = stages_TDF[c("Destination", "Type", "lat_Destination", "lon_Destination", "Date")]
colnames(Destination_Type) = c("Ville", "Type", "lat", "lon", "Date")
Ville_Type = rbind(Origin_Type, Destination_Type)
Ville_Type$Ville <- as.factor(Ville_Type$Ville)
Ville_Type$lat <- as.numeric(Ville_Type$lat)
Ville_Type$lon <- as.numeric(Ville_Type$lon)
# Construction d'un nouveau dataframe avec les infos des villes + le nb de fois où la ville a été visitée
# Séparation temporelle avant ou après 1945
Count_Ville <- Ville_Type %>% group_by(Ville, lon, lat) %>%
  summarize(n = n()) %>%
  arrange(desc(n))
Count_Ville[which(Count_Ville$n >=10),]
Count_Ville$lat <- as.numeric(Count_Ville$lat)
Count_Ville$lon <- as.numeric(Count_Ville$lon)
Count_Ville <- Count_Ville[-which(abs(Count_Ville$lon)>60),]
# On affiche les villes qui ont accueilli le tour de France au moins 4 fois
data = Count_Ville[which(Count_Ville$n > 3),]
# Construction d'un dataframe avec les informations sur les étapes
stages_TDF$Date <- as.Date(stages_TDF$Date, format = "%Y-%m-%d")
Count_Etape <- stages_TDF %>% group_by(Origin, Destination, lon_Origin, lat_Origin, lon_Destination, lat_Destination, Inf_1945 = format(Date, format = "%Y") <= 1945) %>%
  summarize(n = n()) %>%
  arrange(desc(n))
Count_Etape$lat_Destination <- as.numeric(Count_Etape$lat_Destination)
Count_Etape$lon_Destination <- as.numeric(Count_Etape$lon_Destination)
Count_Etape$lat_Origin <- as.numeric(Count_Etape$lat_Origin)
Count_Etape$lon_Origin <- as.numeric(Count_Etape$lon_Origin)
```

```{r  ggplot3, echo = F,  eval = TRUE,  message = FALSE, warning=FALSE}
# Construction de la carte
france <- c(left = -5, bottom = 41, right = 10, top = 51.5)
map <- get_stamenmap(france, zoom = 5, maptype = "terrain-background")

# On affiche les villes
p <- ggmap(map)+
  geom_point( data=data, aes(x=lon, y=lat, size = n, color=n))+
  scale_color_continuous(limits=c(4, max(data$n)), breaks=seq(4, max(data$n), by=20), type = "gradient") +
  guides(color= guide_legend(), size=guide_legend()) +
  scale_size_continuous(limits=c(4, max(data$n)), breaks=seq(4, max(data$n), by=20)) +
  theme_void() + labs(colour = "Nb of times host city", size = "Nb of times host city")
p <-p + new_scale("size") + new_scale_color()

# On affiche les étapes qui ont eu lieu aub moins 3 fois
Count_Etape_lim <- Count_Etape[which(Count_Etape$n >2),]
for (k in 1:nrow(Count_Etape_lim)){
  inter <- as.data.frame(gcIntermediate(c(Count_Etape_lim$lon_Origin[k], Count_Etape_lim$lat_Origin[k]), c(Count_Etape_lim$lon_Destination[k], Count_Etape_lim$lat_Destination[k]), n=50, addStartEnd=TRUE, breakAtDateLine=T))
  names(inter) <- c("long", "lati")
  inter["size"] <- Count_Etape_lim$n[k]
  if (Count_Etape_lim$Inf_1945[k] == TRUE){
    inter["color"] <- "Before 1945"
  } else {
    inter["color"] <- "After 1945"
  }
  p <- p + geom_line(data=inter, aes(x=long, y=lati, color=color, size = size), alpha = 0.70)
}
# On affiche le nom des villes d'accueil qui l'on été au moins 40 fois
pt <- data[which(data$n >40),]
for (k in 1:nrow(pt)){
  p <- p +
    geom_text(data = pt[k,], aes(x = lon, y = lat, label = Ville),
              size = 3, vjust = 0, hjust = -0.25, col="black")
}
p <- p + scale_size_continuous(limits=c(3, max(Count_Etape_lim$n)), breaks=seq(3, max(Count_Etape_lim$n), by=4), range = c(0,2)) + guides(size=guide_legend(ncol=2))  + labs(colour="Time period") + labs(size = "Nb of stages between cities")
p
```


Evolution of distance over time
======================================================================

### Evolution of stages types over time



```{r ggplot5, echo = F,  eval = TRUE,  message = FALSE, warning=FALSE, fig.width = 10}
g1
```

Evolution of stages types over time 
======================================================================

### Evolution of distance over time




```{r ggplot6, echo = F,  eval = TRUE,  message = FALSE, warning=FALSE, fig.width = 10}

g2      
```


Evolution of stages over time
======================================================================


### Evolution of stages over time

```{r  ggplot4, echo = F,  eval = TRUE,  message = FALSE, warning=FALSE}
p
```