---
title: "Explorations"
output: html_document
date: "2022-11-14"
---

---
title: "Graph"
output: html_document
date: "2022-11-14"
---

# Importation des packages

```{r}
library(readr) 
library(dplyr)
```


# Importation des données 

```{r}
stages_TDF <- read.csv("D:/AGROCAMPUS M2/Visualisation de données hétérogènes/Projet/visualisation-tdf/stages_TDF.csv", sep = ";")
```

# Construction dataframe association ville - type d'étape

```{r}
Origin_Type = stages_TDF[c("Origin", "Type")]
colnames(Origin_Type) = c("Ville", "Type")
Destination_Type = stages_TDF[c("Destination", "Type")]
colnames(Destination_Type) = c("Ville", "Type")

Ville_Type = rbind(Origin_Type, Destination_Type)
```

```{r}
Ville_Type$Ville <- as.factor(Ville_Type$Ville)

Count_Ville <- Ville_Type %>% group_by(Ville) %>%
  summarize(n = n()) %>%
  arrange(desc(n))

Count_Ville[which(Count_Ville$n >=10),]
```

# Grouper par étape

```{r}
stages_TDF$Date <- as.Date(stages_TDF$Date, format = "%Y-%m-%d")

Count_Etape <- stages_TDF %>% group_by(Origin, Destination) %>%
  summarize(n = n()) %>%
  arrange(desc(n))

Count_Etape_2000 <- filter(stages_TDF, format(Date, format = "%Y") <= 2000)  %>% 
  group_by(Origin, Destination) %>%
  summarize(n = n(), mean_d = mean(Distance), min_d = min(Distance), max_d = max(Distance)) %>%
  arrange(desc(n))

Count_Etape_2001 <- filter(stages_TDF, format(Date, format = "%Y") > 2000)  %>% 
  group_by(Origin, Destination) %>%
  summarize(n = n(), mean_d = mean(Distance), min_d = min(Distance), max_d = max(Distance)) %>%
  arrange(desc(n))
```


