---
title: "Graph 2"
output: html_document
date: "2022-11-14"
---

```{r}
library(ggplot2)
library(dplyr)
```


#importation + gestion dates

```{r}
tdf=read.csv('C:/Users/BOUADDOUCH Najia/Documents/Projet visu/stages_TDF.csv',sep=';')
tdf$Date <- as.Date(tdf$Date, format = "%Y-%m-%d")
#plot(tdf$Distance~tdf$Date)

```

petit problème sur les types :

```{r}
types= tdf$Type %>%
  unique()
```

On se limite à 5 types : boucle pour remplacer un par un les types 

```{r}
flat=c('Flat','Flat stage','Flat Stage','Half Stage','Plain stage','Plain stage with cobblestones',"Flat cobblestone stage" )
hilly=c('Hilly','Hilly stage','Transition stage','Half Stage','Intermediate stage')
mountain=c('Mountain',"High mountain stage","Medium mountain stage","Mountain Stage" ,"Stage with mountain(s)" ,"Mountain stage" ,"Stage with mountain")
ind_timetrial=c('individual time trial',"Mountain time trial","Individual time trial")
team_timetrial=c('team time trial',"Team time trial")

type=list(flat,hilly,mountain,ind_timetrial,team_timetrial)  #liste de vecteurs

for (i in 1:length(tdf$Type)) {
  for (k in type) {
    if (tdf$Type[i]%in% k) {
      tdf$Type[i]=k[1]
      
    }
  }
}


unique(tdf$Type) #double check
```

Courbes  :

```{r}
ggplot(tdf, aes(x = Date, y = Distance)) + 
  geom_line(aes(color = Type, linetype = Type))  

```

----- Courbes lissées : 

somme des distances par an :

```{r}
tdf$Year= as.numeric(format(tdf$Date, format="%Y"))

tdf %>%
  group_by(Year) %>%
  summarise(dist_totale = sum(Distance))%>%
  as.data.frame()-> dist_totale

```



calcul de la moyenne par type :
```{r}

mean=aggregate(tdf$Distance, list(tdf$Type), FUN=mean) 

```

merge (pour ajouter la distance totale)

```{r}
tdf_bis=merge(tdf,dist_totale,by='Year')

```


```{r}
ggplot(data=tdf_bis,aes(x=Year)) +
  geom_smooth(aes(y=Distance,color=Type),se=F)+
  scale_colour_hue(c=45, l=80)+
  #scale_colour_brewer()+
  #scale_color_manual(values=c('#37305f', '#453d77', '#8979ed','#dcd7fa','#f3f2fd'))+
  #geom_smooth()+
 

  geom_smooth(aes(x=Year,y=dist_totale/10,color='total'),color='#fd3f92',linetype = "dashed",se=F,size=1)+
  #scale_linetype_manual(NULL, values = 1) +
  #scale_color_manual(values = '#F21A00') +
  scale_y_continuous(name = "Distance per stage",
    sec.axis = sec_axis( trans=~.*10, name="Total distance")
  )+
  #geom_hline(yintercept=mean(tdf$Distance), linetype='dashed') +
  #geom_hline(data= mean, aes(yintercept = x,col=Group.1),linetype='dashed',size=0.0001) +
  labs(colour = 'Stage type',face='bold') + 
  labs(y='Distance in km',x='Years' )+ 
  
  theme_grey() +

  theme(
    axis.title.y.right = element_text(color = '#fd3f92',size=12))+
  
  theme(axis.title = element_text(size=12))+

  theme(axis.text.y.right = element_text(face="bold"))+
  theme(legend.position="left")

      
  







  
```




